### ISSUE TITLE
GitHub: Add type: Epic label

### ISSUE THREAD

**Issue by willlarche** [material-motion/material-motion-team#103]

**Comment by pingpongboss** [comment]
Can you explain what an Epic label would be used for?

**Comment by jverkoey** [comment]
Name pending, but the idea would be to capture more open ended "we need to build this thing" tasks. These tasks are like feature requests, but less specific and possibly needing more research.

E.g. "Build a Core Animation Motion Family" isn't really a feature request. Such a task might graduate to a full-blown milestone eventually, but while it's listed as an issue we'd ideally have some way to categorize these types of tasks.

Perhaps "type: potential milestone" ?

**Comment by willlarche** [comment]
Not exactly, tho those things will be captured too.

It's because we have so many issues for so many features and so many repos
that a flat hierarchy isn't cutting it.

Epics are Plan, Performer, Scheduler, Transaction. The big things. Purely
organizational.

Most repos won't need them at all: transitions repo is a repo for an epic.
Done. But runtime is a collection of big things.

Right now it's very difficult (actually impossible) to have a piece of
metadata that exists in more than one milestone. If you wanted to see all
tickets related to Plan, Performer, Transaction you can't. They are
(correctly) distributed into the milestones

And the word don't mean a thing. Feel free to propose.

**Comment by jverkoey** [comment]
Projects now supports this desired behavior.
