### ISSUE TITLE
iOS Repos: Add '.private_header_files' value to pod spec

### ISSUE THREAD

**Issue by willlarche** [material-motion/material-motion-team#106]
Here is an example from runtime

Pod::Spec.new do |s|
  s.name         = "MaterialMotionRuntime"
  s.summary      = "Material Motion Runtime for Apple Devices"
  s.version      = "1.0.0"
  s.authors      = "The Material Motion Authors."
  s.license      = "Apache 2.0"
  s.homepage     = "https://github.com/material-motion/material-motion-runtime-objc"
  s.source       = { :path => "./" }
  s.platform     = :ios, "8.0"
  s.requires_arc = true

  s.public_header_files = "src/_.h"
  s.private_header_files = "src/private/_.h"
  s.source_files = "src/*_/_.{h,m}"
  s.header_mappings_dir = "src"
end

**Comment by willlarche** [comment]
Change in yeoman generator too.

**Comment by jverkoey** [comment]
Is unclear that we need this.
