### ISSUE TITLE
Open source

### ISSUE THREAD

**Issue by jverkoey** [material-motion/material-motion-team#12]
This thread outlines the steps we'll take to flip our open source bits.

Verify for every GitHub repo:
- issues are turned on
- wiki is turned off
- squash and merge is the default operation.
- There is a develop branch, and it is the default.
- There is no master branch.
- Enable branch protection on `develop`.
  - Enable "Protect this branch"
  - Enable "Restrict who can push to this branch"
  - Add the relevant "regular contributors" team for that platform.
  - Add the core team.
- Enable branch protection on `stable`, if it's available.
  - Enable "Protect this branch"
  - Enable "Restrict who can push to this branch"
  - Add the core team.
- LICENSE exists and is Apache 2.0
- CONTRIBUTING.md exists
- AUTHORS exists
- Delete any CONTRIBUTORS file
- README.md exists and includes license blurb.
```
## License

Licensed under the Apache 2.0 license. See LICENSE for details.
```
- Verify that every source file has the correct header.

- [x] material-motion/material-motion-starmap
- [x] material-motion/material-motion-experiments-js
- [x] material-motion/material-motion-experiments-swift
- [x] material-motion/material-motion-experiments-objc
- [x] material-motion/material-motion-experiments-android
- [x] material-motion/material-motion-conventions-android
- [x] material-motion/material-motion-team
- [x] material-motion/material-motion-hubot
- [x] material-motion/material-motion-expression-android
- [x] material-motion/material-motion-family-tween-android
- [x] material-motion/material-motion-direct-web
- [x] material-motion/material-motion-runtime-objc
- [x] material-motion/material-motion-runtime-android
- [x] material-motion/material-motion-transitions-objc
- [x] material-motion/cocoapods-catalog-by-convention
- [x] material-motion/gh

- [x] Ensure that all of our repos are being mapped in codereview.cc.
- [x] Declare comment bankruptcy for starmap
- [x] Declare comment bankruptcy for team docs
- [x] Flip the public bits on Discord.
- [x] Flip the public bits on GitBook Starmap and team docs.
- [x] Flip the public bits on all GitHub repos.
- [x] Flip the public bits for codereview.cc.

- [x] appsforartists' handle is public to [public](https://github.com/orgs/material-motion/people)
- [x] featherless' handle is public to [public](https://github.com/orgs/material-motion/people)
- [x] markwei's handle is public to [public](https://github.com/orgs/material-motion/people)
- [x] willlarche's handle is public to [public](https://github.com/orgs/material-motion/people)

**Comment by appsforartists** [comment]
- [x] Set yoself to [public](https://github.com/orgs/material-motion/people) and rock our MM badge _(optional)_

**Comment by pingpongboss** [comment]
Add to checklist the 3 googlegroups

**Comment by jverkoey** [comment]
We done!
