### ISSUE TITLE
Spec out what the Github issue labels mean

### ISSUE THREAD

**Issue by pingpongboss** [material-motion/material-motion-team#15]

**Comment by jverkoey** [comment]
There are three categories of label:
- `flow`
- `type`
- `where`

Flow defines the current activity of the issue. Is it being worked on? Is it blocked? Issues generally only have one flow label.

Type defines the kind of issue it is. Is it a bug? Feature request? API change? May have many types.

Where defines the affected feature within the repo. This is primarily for repos that have more than one feature within them. Monorepos, for example, will have many of these labels. For "one-feature, one-repo" repos we usually won't need a "where" label.

**Comment by jverkoey** [comment]
I've spec'd this out here:

https://material-motion.gitbooks.io/material-motion-team/content/essentials/issues.html
