### ISSUE TITLE
Dead link: Starmap contributing: patch process: governence

### ISSUE THREAD

**Issue by willlarche** [material-motion/material-motion-team#17]
![screen shot 2016-07-01 at 5 03 56 pm](https://cloud.githubusercontent.com/assets/1271525/16534462/e6394bc4-3fad-11e6-8d81-1c57d1b5c905.png)

**Comment by jverkoey** [comment]
Fixed. https://material-motion.gitbooks.io/material-motion-team/content/starmap_essentials/
