### ISSUE TITLE
Generate badges/shields table automatically

### ISSUE THREAD

**Issue by pingpongboss** [material-motion/material-motion-team#173]
Create a tool to generate the contents of https://material-motion.github.io/material-motion/ automatically. 

This tool should also generate a text version of the table for weekly updates.

**Comment by jverkoey** [comment]
To get all repos:
```
curl -i https://api.github.com/orgs/material-motion/repos | grep full_name | cut -d: -f2
```

**Comment by jverkoey** [comment]
```
# Generate a markdown table with images
mdm shields table

# Generate a markdown table with text (must hit .json shields.io api)
mdm shields table astext
```

**Comment by appsforartists** [comment]
it is my duty as the resident web guy to post the js equivalent:

```javascript
fetch(
  'https://api.github.com/orgs/material-motion/repos'
).then(
  response => response.json()
).then(
  repos => repos.map(
    repo => repo.full_name
  )
).then(
  fullNames => {
    // do something with fullNames here
    console.log(fullNames);
  }
)
```

**Comment by pingpongboss** [comment]
We're like a little sitcom. We've each got our own roles.

**Comment by appsforartists** [comment]
Battery's dying, but here's a sketch:

```javascript
fetch(
  'https://api.github.com/orgs/material-motion/repos?per_page=100'
).then(
  response => response.json()
).then(
  repos => repos.map(
    repo => (
      {
        orgAndRepoSlug: repo.full_name,
        docsURL: repo.homepage,
      }
    ) 
  )
).then(
  repoMetadata => (
    {
      android: repoMetadata.filter(
        ({ orgAndRepoSlug }) => orgAndRepoSlug.endsWith('android')
      ),
      js: repoMetadata.filter(
        ({ orgAndRepoSlug }) => orgAndRepoSlug.endsWith('js')
      ),
      apple: repoMetadata.filter(
        ({ orgAndRepoSlug }) => orgAndRepoSlug.endsWith('swift') || orgAndRepoSlug.endsWith('objc')
      ),
    }
  )
).then(
  ({ android, js, apple }) => (
    {
      android: android.map(
        ({ orgAndRepoSlug, docsURL }) => [
          `[${ orgAndRepoSlug }](https://github.com/${ orgAndRepoSlug }/)`,
          `[![Build Status](https://travis-ci.org/${ orgAndRepoSlug }.svg?branch=develop)](https://travis-ci.org/${ orgAndRepoSlug }/)`,
          `[![codecov](https://codecov.io/gh/${ orgAndRepoSlug }/branch/develop/graph/badge.svg)](https://codecov.io/gh/${ orgAndRepoSlug }/)`,
          `[![Release](https://img.shields.io/github/release/${ orgAndRepoSlug }.svg)](https://github.com/${ orgAndRepoSlug }/releases/latest/)`,
          `[![Docs](https://img.shields.io/badge/jitpack-docs-green.svg)](${ docsURL })`,
          `[![Open issues](https://img.shields.io/github/issues/${ orgAndRepoSlug }.svg)](https://github.com/${ orgAndRepoSlug }/issues/)`,
        ]
      ),
      js: js.map(
        ({ orgAndRepoSlug, docsURL }) => {
          const packageName = orgAndRepoSlug.split('/').pop().replace('-js', '');

          return [
            `[${ orgAndRepoSlug }](https://github.com/${ orgAndRepoSlug })`,
            `[![Build Status](https://travis-ci.org/${ orgAndRepoSlug }.svg?branch=develop)](https://travis-ci.org/${ orgAndRepoSlug }/)`,
            `[![codecov](https://codecov.io/gh/${ orgAndRepoSlug }/branch/develop/graph/badge.svg)](https://codecov.io/gh/${ orgAndRepoSlug }/)`,
            `[![Release](https://img.shields.io/npm/v/${ packageName }.svg)](https://www.npmjs.com/package/${ packageName }/)`,
            `[![Open issues](https://img.shields.io/github/issues/${ orgAndRepoSlug }.svg)](https://github.com/${ orgAndRepoSlug }/issues/)`,
          ]
        }
      ),
      apple: apple.map(
        ({ orgAndRepoSlug, docsURL }) => {
          const packageName = docsURL
            ? (/http:\/\/cocoadocs.org\/docsets\/(\w+)/.exec(docsURL) || []).pop()
            : console.warn(`${ orgAndRepoSlug } doesn't have homepage set correctly!`) || '';

          return [
            `[${ orgAndRepoSlug }](https://github.com/${ orgAndRepoSlug })`,
            `[![Build Status](https://travis-ci.org/${ orgAndRepoSlug }.svg?branch=develop)](https://travis-ci.org/${ orgAndRepoSlug }/)`,
            `[![codecov](https://codecov.io/gh/${ orgAndRepoSlug }/branch/develop/graph/badge.svg)](https://codecov.io/gh/${ orgAndRepoSlug }/)`,
            `[![CocoaPods Compatible](https://img.shields.io/cocoapods/v/${ packageName }.svg)](https://cocoapods.org/pods/${ packageName }/)`,
            `[![Platform](https://img.shields.io/cocoapods/p/${ packageName }.svg)](http://cocoadocs.org/docsets/${ packageName })`,
            `[![Docs](https://img.shields.io/cocoapods/metrics/doc-percent/${ packageName }.svg)](${ docsURL })`,
            `[![Open issues](https://img.shields.io/github/issues/${ orgAndRepoSlug }.svg)](https://github.com/${ orgAndRepoSlug }/issues/)`,
          ]
        }
      ),
    }
  )
).then(
  ({ apple, android, js }) => `
## Apple platform support
| Library | Build status | Coverage | Version | Platforms | Docs | Issues | 
|---------|:------------:|:--------:|:-------:|:---------:|:----:|:------:|
${ apple.map(repo => `| ${ repo.join(' | ') } |`).join('\n') }

## Android platform support


| Library | Build status | Coverage | Version | Docs | Issues |
|---------|:------------:|:--------:|:-------:|:----:|:------:|
${ android.map(repo => `| ${ repo.join(' | ') } |`).join('\n') }

## Web platform support

| Library | Build status | Coverage | Version | Issues |
|---------|:------------:|:--------:|:-------:|:------:|
${ js.map(repo => `| ${ repo.join(' | ') } |`).join('\n') }
`
).then(console.log)
```

**Comment by appsforartists** [comment]
## Apple platform support
| Library | Build status | Coverage | Version | Platforms | Docs | Issues | 
|---------|:------------:|:--------:|:-------:|:---------:|:----:|:------:|
| [material-motion/experiments-swift](https://github.com/material-motion/experiments-swift) | [![Build Status](https://travis-ci.org/material-motion/experiments-swift.svg?branch=develop)](https://travis-ci.org/material-motion/experiments-swift/) | [![codecov](https://codecov.io/gh/material-motion/experiments-swift/branch/develop/graph/badge.svg)](https://codecov.io/gh/material-motion/experiments-swift/) | [![CocoaPods Compatible](https://img.shields.io/cocoapods/v/.svg)](https://cocoapods.org/pods//) | [![Platform](https://img.shields.io/cocoapods/p/.svg)](http://cocoadocs.org/docsets/) | [![Docs](https://img.shields.io/cocoapods/metrics/doc-percent/.svg)]() | [![Open issues](https://img.shields.io/github/issues/material-motion/experiments-swift.svg)](https://github.com/material-motion/experiments-swift/issues/) |
| [material-motion/material-motion-experiments-objc](https://github.com/material-motion/material-motion-experiments-objc) | [![Build Status](https://travis-ci.org/material-motion/material-motion-experiments-objc.svg?branch=develop)](https://travis-ci.org/material-motion/material-motion-experiments-objc/) | [![codecov](https://codecov.io/gh/material-motion/material-motion-experiments-objc/branch/develop/graph/badge.svg)](https://codecov.io/gh/material-motion/material-motion-experiments-objc/) | [![CocoaPods Compatible](https://img.shields.io/cocoapods/v/.svg)](https://cocoapods.org/pods//) | [![Platform](https://img.shields.io/cocoapods/p/.svg)](http://cocoadocs.org/docsets/) | [![Docs](https://img.shields.io/cocoapods/metrics/doc-percent/.svg)]() | [![Open issues](https://img.shields.io/github/issues/material-motion/material-motion-experiments-objc.svg)](https://github.com/material-motion/material-motion-experiments-objc/issues/) |
| [material-motion/runtime-objc](https://github.com/material-motion/runtime-objc) | [![Build Status](https://travis-ci.org/material-motion/runtime-objc.svg?branch=develop)](https://travis-ci.org/material-motion/runtime-objc/) | [![codecov](https://codecov.io/gh/material-motion/runtime-objc/branch/develop/graph/badge.svg)](https://codecov.io/gh/material-motion/runtime-objc/) | [![CocoaPods Compatible](https://img.shields.io/cocoapods/v/MaterialMotionRuntime.svg)](https://cocoapods.org/pods/MaterialMotionRuntime/) | [![Platform](https://img.shields.io/cocoapods/p/MaterialMotionRuntime.svg)](http://cocoadocs.org/docsets/MaterialMotionRuntime) | [![Docs](https://img.shields.io/cocoapods/metrics/doc-percent/MaterialMotionRuntime.svg)](http://cocoadocs.org/docsets/MaterialMotionRuntime/) | [![Open issues](https://img.shields.io/github/issues/material-motion/runtime-objc.svg)](https://github.com/material-motion/runtime-objc/issues/) |
| [material-motion/transitions-objc](https://github.com/material-motion/transitions-objc) | [![Build Status](https://travis-ci.org/material-motion/transitions-objc.svg?branch=develop)](https://travis-ci.org/material-motion/transitions-objc/) | [![codecov](https://codecov.io/gh/material-motion/transitions-objc/branch/develop/graph/badge.svg)](https://codecov.io/gh/material-motion/transitions-objc/) | [![CocoaPods Compatible](https://img.shields.io/cocoapods/v/MaterialMotionTransitions.svg)](https://cocoapods.org/pods/MaterialMotionTransitions/) | [![Platform](https://img.shields.io/cocoapods/p/MaterialMotionTransitions.svg)](http://cocoadocs.org/docsets/MaterialMotionTransitions) | [![Docs](https://img.shields.io/cocoapods/metrics/doc-percent/MaterialMotionTransitions.svg)](http://cocoadocs.org/docsets/MaterialMotionTransitions/) | [![Open issues](https://img.shields.io/github/issues/material-motion/transitions-objc.svg)](https://github.com/material-motion/transitions-objc/issues/) |
| [material-motion/conventions-objc](https://github.com/material-motion/conventions-objc) | [![Build Status](https://travis-ci.org/material-motion/conventions-objc.svg?branch=develop)](https://travis-ci.org/material-motion/conventions-objc/) | [![codecov](https://codecov.io/gh/material-motion/conventions-objc/branch/develop/graph/badge.svg)](https://codecov.io/gh/material-motion/conventions-objc/) | [![CocoaPods Compatible](https://img.shields.io/cocoapods/v/.svg)](https://cocoapods.org/pods//) | [![Platform](https://img.shields.io/cocoapods/p/.svg)](http://cocoadocs.org/docsets/) | [![Docs](https://img.shields.io/cocoapods/metrics/doc-percent/.svg)]() | [![Open issues](https://img.shields.io/github/issues/material-motion/conventions-objc.svg)](https://github.com/material-motion/conventions-objc/issues/) |
| [material-motion/coreanimation-swift](https://github.com/material-motion/coreanimation-swift) | [![Build Status](https://travis-ci.org/material-motion/coreanimation-swift.svg?branch=develop)](https://travis-ci.org/material-motion/coreanimation-swift/) | [![codecov](https://codecov.io/gh/material-motion/coreanimation-swift/branch/develop/graph/badge.svg)](https://codecov.io/gh/material-motion/coreanimation-swift/) | [![CocoaPods Compatible](https://img.shields.io/cocoapods/v/MaterialMotionCoreAnimation.svg)](https://cocoapods.org/pods/MaterialMotionCoreAnimation/) | [![Platform](https://img.shields.io/cocoapods/p/MaterialMotionCoreAnimation.svg)](http://cocoadocs.org/docsets/MaterialMotionCoreAnimation) | [![Docs](https://img.shields.io/cocoapods/metrics/doc-percent/MaterialMotionCoreAnimation.svg)](http://cocoadocs.org/docsets/MaterialMotionCoreAnimation/) | [![Open issues](https://img.shields.io/github/issues/material-motion/coreanimation-swift.svg)](https://github.com/material-motion/coreanimation-swift/issues/) |
| [material-motion/direct-manipulation-swift](https://github.com/material-motion/direct-manipulation-swift) | [![Build Status](https://travis-ci.org/material-motion/direct-manipulation-swift.svg?branch=develop)](https://travis-ci.org/material-motion/direct-manipulation-swift/) | [![codecov](https://codecov.io/gh/material-motion/direct-manipulation-swift/branch/develop/graph/badge.svg)](https://codecov.io/gh/material-motion/direct-manipulation-swift/) | [![CocoaPods Compatible](https://img.shields.io/cocoapods/v/MaterialMotionDirectManipulation.svg)](https://cocoapods.org/pods/MaterialMotionDirectManipulation/) | [![Platform](https://img.shields.io/cocoapods/p/MaterialMotionDirectManipulation.svg)](http://cocoadocs.org/docsets/MaterialMotionDirectManipulation) | [![Docs](https://img.shields.io/cocoapods/metrics/doc-percent/MaterialMotionDirectManipulation.svg)](http://cocoadocs.org/docsets/MaterialMotionDirectManipulation/) | [![Open issues](https://img.shields.io/github/issues/material-motion/direct-manipulation-swift.svg)](https://github.com/material-motion/direct-manipulation-swift/issues/) |
| [material-motion/pop-swift](https://github.com/material-motion/pop-swift) | [![Build Status](https://travis-ci.org/material-motion/pop-swift.svg?branch=develop)](https://travis-ci.org/material-motion/pop-swift/) | [![codecov](https://codecov.io/gh/material-motion/pop-swift/branch/develop/graph/badge.svg)](https://codecov.io/gh/material-motion/pop-swift/) | [![CocoaPods Compatible](https://img.shields.io/cocoapods/v/MaterialMotionPopFamily.svg)](https://cocoapods.org/pods/MaterialMotionPopFamily/) | [![Platform](https://img.shields.io/cocoapods/p/MaterialMotionPopFamily.svg)](http://cocoadocs.org/docsets/MaterialMotionPopFamily) | [![Docs](https://img.shields.io/cocoapods/metrics/doc-percent/MaterialMotionPopFamily.svg)](http://cocoadocs.org/docsets/MaterialMotionPopFamily) | [![Open issues](https://img.shields.io/github/issues/material-motion/pop-swift.svg)](https://github.com/material-motion/pop-swift/issues/) |
| [material-motion/catalog-swift](https://github.com/material-motion/catalog-swift) | [![Build Status](https://travis-ci.org/material-motion/catalog-swift.svg?branch=develop)](https://travis-ci.org/material-motion/catalog-swift/) | [![codecov](https://codecov.io/gh/material-motion/catalog-swift/branch/develop/graph/badge.svg)](https://codecov.io/gh/material-motion/catalog-swift/) | [![CocoaPods Compatible](https://img.shields.io/cocoapods/v/.svg)](https://cocoapods.org/pods//) | [![Platform](https://img.shields.io/cocoapods/p/.svg)](http://cocoadocs.org/docsets/) | [![Docs](https://img.shields.io/cocoapods/metrics/doc-percent/.svg)]() | [![Open issues](https://img.shields.io/github/issues/material-motion/catalog-swift.svg)](https://github.com/material-motion/catalog-swift/issues/) |
| [material-motion/coreanimation-transitions-swift](https://github.com/material-motion/coreanimation-transitions-swift) | [![Build Status](https://travis-ci.org/material-motion/coreanimation-transitions-swift.svg?branch=develop)](https://travis-ci.org/material-motion/coreanimation-transitions-swift/) | [![codecov](https://codecov.io/gh/material-motion/coreanimation-transitions-swift/branch/develop/graph/badge.svg)](https://codecov.io/gh/material-motion/coreanimation-transitions-swift/) | [![CocoaPods Compatible](https://img.shields.io/cocoapods/v/MaterialMotionCoreAnimationTransitions.svg)](https://cocoapods.org/pods/MaterialMotionCoreAnimationTransitions/) | [![Platform](https://img.shields.io/cocoapods/p/MaterialMotionCoreAnimationTransitions.svg)](http://cocoadocs.org/docsets/MaterialMotionCoreAnimationTransitions) | [![Docs](https://img.shields.io/cocoapods/metrics/doc-percent/MaterialMotionCoreAnimationTransitions.svg)](http://cocoadocs.org/docsets/MaterialMotionCoreAnimationTransitions/) | [![Open issues](https://img.shields.io/github/issues/material-motion/coreanimation-transitions-swift.svg)](https://github.com/material-motion/coreanimation-transitions-swift/issues/) |
| [material-motion/pop-transitions-swift](https://github.com/material-motion/pop-transitions-swift) | [![Build Status](https://travis-ci.org/material-motion/pop-transitions-swift.svg?branch=develop)](https://travis-ci.org/material-motion/pop-transitions-swift/) | [![codecov](https://codecov.io/gh/material-motion/pop-transitions-swift/branch/develop/graph/badge.svg)](https://codecov.io/gh/material-motion/pop-transitions-swift/) | [![CocoaPods Compatible](https://img.shields.io/cocoapods/v/MaterialMotionPopTransitions.svg)](https://cocoapods.org/pods/MaterialMotionPopTransitions/) | [![Platform](https://img.shields.io/cocoapods/p/MaterialMotionPopTransitions.svg)](http://cocoadocs.org/docsets/MaterialMotionPopTransitions) | [![Docs](https://img.shields.io/cocoapods/metrics/doc-percent/MaterialMotionPopTransitions.svg)](http://cocoadocs.org/docsets/MaterialMotionPopTransitions/) | [![Open issues](https://img.shields.io/github/issues/material-motion/pop-transitions-swift.svg)](https://github.com/material-motion/pop-transitions-swift/issues/) |
| [material-motion/indefinite-observable-swift](https://github.com/material-motion/indefinite-observable-swift) | [![Build Status](https://travis-ci.org/material-motion/indefinite-observable-swift.svg?branch=develop)](https://travis-ci.org/material-motion/indefinite-observable-swift/) | [![codecov](https://codecov.io/gh/material-motion/indefinite-observable-swift/branch/develop/graph/badge.svg)](https://codecov.io/gh/material-motion/indefinite-observable-swift/) | [![CocoaPods Compatible](https://img.shields.io/cocoapods/v/IndefiniteObservable.svg)](https://cocoapods.org/pods/IndefiniteObservable/) | [![Platform](https://img.shields.io/cocoapods/p/IndefiniteObservable.svg)](http://cocoadocs.org/docsets/IndefiniteObservable) | [![Docs](https://img.shields.io/cocoapods/metrics/doc-percent/IndefiniteObservable.svg)](http://cocoadocs.org/docsets/IndefiniteObservable/) | [![Open issues](https://img.shields.io/github/issues/material-motion/indefinite-observable-swift.svg)](https://github.com/material-motion/indefinite-observable-swift/issues/) |

## Android platform support


| Library | Build status | Coverage | Version | Docs | Issues |
|---------|:------------:|:--------:|:-------:|:----:|:------:|
| [material-motion/experiments-android](https://github.com/material-motion/experiments-android/) | [![Build Status](https://travis-ci.org/material-motion/experiments-android.svg?branch=develop)](https://travis-ci.org/material-motion/experiments-android/) | [![codecov](https://codecov.io/gh/material-motion/experiments-android/branch/develop/graph/badge.svg)](https://codecov.io/gh/material-motion/experiments-android/) | [![Release](https://img.shields.io/github/release/material-motion/experiments-android.svg)](https://github.com/material-motion/experiments-android/releases/latest/) | [![Docs](https://img.shields.io/badge/jitpack-docs-green.svg)]() | [![Open issues](https://img.shields.io/github/issues/material-motion/experiments-android.svg)](https://github.com/material-motion/experiments-android/issues/) |
| [material-motion/conventions-android](https://github.com/material-motion/conventions-android/) | [![Build Status](https://travis-ci.org/material-motion/conventions-android.svg?branch=develop)](https://travis-ci.org/material-motion/conventions-android/) | [![codecov](https://codecov.io/gh/material-motion/conventions-android/branch/develop/graph/badge.svg)](https://codecov.io/gh/material-motion/conventions-android/) | [![Release](https://img.shields.io/github/release/material-motion/conventions-android.svg)](https://github.com/material-motion/conventions-android/releases/latest/) | [![Docs](https://img.shields.io/badge/jitpack-docs-green.svg)](null) | [![Open issues](https://img.shields.io/github/issues/material-motion/conventions-android.svg)](https://github.com/material-motion/conventions-android/issues/) |
| [material-motion/expression-android](https://github.com/material-motion/expression-android/) | [![Build Status](https://travis-ci.org/material-motion/expression-android.svg?branch=develop)](https://travis-ci.org/material-motion/expression-android/) | [![codecov](https://codecov.io/gh/material-motion/expression-android/branch/develop/graph/badge.svg)](https://codecov.io/gh/material-motion/expression-android/) | [![Release](https://img.shields.io/github/release/material-motion/expression-android.svg)](https://github.com/material-motion/expression-android/releases/latest/) | [![Docs](https://img.shields.io/badge/jitpack-docs-green.svg)](null) | [![Open issues](https://img.shields.io/github/issues/material-motion/expression-android.svg)](https://github.com/material-motion/expression-android/issues/) |
| [material-motion/family-tween-android](https://github.com/material-motion/family-tween-android/) | [![Build Status](https://travis-ci.org/material-motion/family-tween-android.svg?branch=develop)](https://travis-ci.org/material-motion/family-tween-android/) | [![codecov](https://codecov.io/gh/material-motion/family-tween-android/branch/develop/graph/badge.svg)](https://codecov.io/gh/material-motion/family-tween-android/) | [![Release](https://img.shields.io/github/release/material-motion/family-tween-android.svg)](https://github.com/material-motion/family-tween-android/releases/latest/) | [![Docs](https://img.shields.io/badge/jitpack-docs-green.svg)]() | [![Open issues](https://img.shields.io/github/issues/material-motion/family-tween-android.svg)](https://github.com/material-motion/family-tween-android/issues/) |
| [material-motion/runtime-android](https://github.com/material-motion/runtime-android/) | [![Build Status](https://travis-ci.org/material-motion/runtime-android.svg?branch=develop)](https://travis-ci.org/material-motion/runtime-android/) | [![codecov](https://codecov.io/gh/material-motion/runtime-android/branch/develop/graph/badge.svg)](https://codecov.io/gh/material-motion/runtime-android/) | [![Release](https://img.shields.io/github/release/material-motion/runtime-android.svg)](https://github.com/material-motion/runtime-android/releases/latest/) | [![Docs](https://img.shields.io/badge/jitpack-docs-green.svg)](https://jitpack.io/com/github/material-motion/runtime-android/5.0.0/javadoc/) | [![Open issues](https://img.shields.io/github/issues/material-motion/runtime-android.svg)](https://github.com/material-motion/runtime-android/issues/) |
| [material-motion/transitions-android](https://github.com/material-motion/transitions-android/) | [![Build Status](https://travis-ci.org/material-motion/transitions-android.svg?branch=develop)](https://travis-ci.org/material-motion/transitions-android/) | [![codecov](https://codecov.io/gh/material-motion/transitions-android/branch/develop/graph/badge.svg)](https://codecov.io/gh/material-motion/transitions-android/) | [![Release](https://img.shields.io/github/release/material-motion/transitions-android.svg)](https://github.com/material-motion/transitions-android/releases/latest/) | [![Docs](https://img.shields.io/badge/jitpack-docs-green.svg)]() | [![Open issues](https://img.shields.io/github/issues/material-motion/transitions-android.svg)](https://github.com/material-motion/transitions-android/issues/) |
| [material-motion/family-rebound-android](https://github.com/material-motion/family-rebound-android/) | [![Build Status](https://travis-ci.org/material-motion/family-rebound-android.svg?branch=develop)](https://travis-ci.org/material-motion/family-rebound-android/) | [![codecov](https://codecov.io/gh/material-motion/family-rebound-android/branch/develop/graph/badge.svg)](https://codecov.io/gh/material-motion/family-rebound-android/) | [![Release](https://img.shields.io/github/release/material-motion/family-rebound-android.svg)](https://github.com/material-motion/family-rebound-android/releases/latest/) | [![Docs](https://img.shields.io/badge/jitpack-docs-green.svg)]() | [![Open issues](https://img.shields.io/github/issues/material-motion/family-rebound-android.svg)](https://github.com/material-motion/family-rebound-android/issues/) |
| [material-motion/family-direct-manipulation-android](https://github.com/material-motion/family-direct-manipulation-android/) | [![Build Status](https://travis-ci.org/material-motion/family-direct-manipulation-android.svg?branch=develop)](https://travis-ci.org/material-motion/family-direct-manipulation-android/) | [![codecov](https://codecov.io/gh/material-motion/family-direct-manipulation-android/branch/develop/graph/badge.svg)](https://codecov.io/gh/material-motion/family-direct-manipulation-android/) | [![Release](https://img.shields.io/github/release/material-motion/family-direct-manipulation-android.svg)](https://github.com/material-motion/family-direct-manipulation-android/releases/latest/) | [![Docs](https://img.shields.io/badge/jitpack-docs-green.svg)]() | [![Open issues](https://img.shields.io/github/issues/material-motion/family-direct-manipulation-android.svg)](https://github.com/material-motion/family-direct-manipulation-android/issues/) |
| [material-motion/gestures-android](https://github.com/material-motion/gestures-android/) | [![Build Status](https://travis-ci.org/material-motion/gestures-android.svg?branch=develop)](https://travis-ci.org/material-motion/gestures-android/) | [![codecov](https://codecov.io/gh/material-motion/gestures-android/branch/develop/graph/badge.svg)](https://codecov.io/gh/material-motion/gestures-android/) | [![Release](https://img.shields.io/github/release/material-motion/gestures-android.svg)](https://github.com/material-motion/gestures-android/releases/latest/) | [![Docs](https://img.shields.io/badge/jitpack-docs-green.svg)]() | [![Open issues](https://img.shields.io/github/issues/material-motion/gestures-android.svg)](https://github.com/material-motion/gestures-android/issues/) |
| [material-motion/catalog-android](https://github.com/material-motion/catalog-android/) | [![Build Status](https://travis-ci.org/material-motion/catalog-android.svg?branch=develop)](https://travis-ci.org/material-motion/catalog-android/) | [![codecov](https://codecov.io/gh/material-motion/catalog-android/branch/develop/graph/badge.svg)](https://codecov.io/gh/material-motion/catalog-android/) | [![Release](https://img.shields.io/github/release/material-motion/catalog-android.svg)](https://github.com/material-motion/catalog-android/releases/latest/) | [![Docs](https://img.shields.io/badge/jitpack-docs-green.svg)]() | [![Open issues](https://img.shields.io/github/issues/material-motion/catalog-android.svg)](https://github.com/material-motion/catalog-android/issues/) |

## Web platform support

| Library | Build status | Coverage | Version | Issues |
|---------|:------------:|:--------:|:-------:|:------:|
| [material-motion/material-motion-js](https://github.com/material-motion/material-motion-js) | [![Build Status](https://travis-ci.org/material-motion/material-motion-js.svg?branch=develop)](https://travis-ci.org/material-motion/material-motion-js/) | [![codecov](https://codecov.io/gh/material-motion/material-motion-js/branch/develop/graph/badge.svg)](https://codecov.io/gh/material-motion/material-motion-js/) | [![Release](https://img.shields.io/npm/v/material-motion-js.svg)](https://www.npmjs.com/package/material-motion-js/) | [![Open issues](https://img.shields.io/github/issues/material-motion/material-motion-js.svg)](https://github.com/material-motion/material-motion-js/issues/) |
| [material-motion/streams-experiment-js](https://github.com/material-motion/streams-experiment-js) | [![Build Status](https://travis-ci.org/material-motion/streams-experiment-js.svg?branch=develop)](https://travis-ci.org/material-motion/streams-experiment-js/) | [![codecov](https://codecov.io/gh/material-motion/streams-experiment-js/branch/develop/graph/badge.svg)](https://codecov.io/gh/material-motion/streams-experiment-js/) | [![Release](https://img.shields.io/npm/v/streams-experiment-js.svg)](https://www.npmjs.com/package/streams-experiment-js/) | [![Open issues](https://img.shields.io/github/issues/material-motion/streams-experiment-js.svg)](https://github.com/material-motion/streams-experiment-js/issues/) |
| [material-motion/indefinite-observable-js](https://github.com/material-motion/indefinite-observable-js) | [![Build Status](https://travis-ci.org/material-motion/indefinite-observable-js.svg?branch=develop)](https://travis-ci.org/material-motion/indefinite-observable-js/) | [![codecov](https://codecov.io/gh/material-motion/indefinite-observable-js/branch/develop/graph/badge.svg)](https://codecov.io/gh/material-motion/indefinite-observable-js/) | [![Release](https://img.shields.io/npm/v/indefinite-observable-js.svg)](https://www.npmjs.com/package/indefinite-observable-js/) | [![Open issues](https://img.shields.io/github/issues/material-motion/indefinite-observable-js.svg)](https://github.com/material-motion/indefinite-observable-js/issues/) |

**Comment by appsforartists** [comment]
Hmm... I don't see indefinite-observable in either chart

**Comment by jverkoey** [comment]
- [ ] Strip org name from first column.
- [x] Figure out why some packages are missing.
- [ ] Check headers for extra pages and follow them if they exist
- [ ] Hide docs badge when docsURL is blank.
- [ ] clean up docsURL tests
- [x] All of the CocoaDocs documentation badges are pointing to MaterialMotionDirectManipulation for some reason.
- [ ] Sort the repos by name.
- [ ] parse material-motion-js/packages and include them

**Comment by appsforartists** [comment]
I tested the regex on a real URL and forgot to replace with docsURL.  fixed that bit

**Comment by appsforartists** [comment]
For JS: https://api.github.com/repos/material-motion/material-motion-js/contents/packages?ref=stable

**Comment by appsforartists** [comment]
TODO: move checkboxes to issues
