### ISSUE TITLE
mdm dir <repo>

### ISSUE THREAD

**Issue by jverkoey** [material-motion/material-motion-team#19]
`mdm dir [repo]`

Output the directory for the given repo, if it exists on disk.

This tool will use a convention-oriented approach to finding repos. It will use the following heuristics:
- If `[repo]` has `material-motion-` prefix, remove it.
- Check existence of folder named `[repo]` or `material-motion-[repo]` adjacent to `mdm`'s git repository.
- If either exists, output the complete path.

**Comment by jverkoey** [comment]
Idea of this tool is that it can be piped to cd to quickly jump between directories:

```
cd $(mdm dir team)
```

**Comment by pingpongboss** [comment]
Also, since it's relatively rare for any of us to have more than 2 platform repos, maybe also infer `-platform`.

So `mdm dir runtime` returns `material-motion-runtime-android` for me.

**Comment by jverkoey** [comment]
Oooh, good idea :)
