### ISSUE TITLE
mdm release publish should open the github release url after showing instructions

### ISSUE THREAD

**Issue by jverkoey** [material-motion/material-motion-team#58]
Ideally the command will show instructions and then require the user to hit "Enter" before punting to the web browser.

**Comment by pingpongboss** [comment]
Or take in a --argument flag.

**Comment by jverkoey** [comment]
🎊 My diff is ready for review at http://codereview.cc/D1177

**Comment by jverkoey** [comment]
What would the argument be?

**Comment by pingpongboss** [comment]
Like `arc diff --browse`

**Comment by jverkoey** [comment]
Ah, interesting. I think we always want to open the url as part of this workflow. In that case the argument would be `--nobrowse`. What do you think?

**Comment by pingpongboss** [comment]
I would disagree, but my [remote] workflow is special. I almost never want
to open the browser while working in a remote terminal. I always prefer the
URL to be printed so i can open it in a local browser.

**Comment by jverkoey** [comment]
I can buy that. Assuming we go that route, we'll need to find a way to make it abundantly clear that you have to visit the URL in order to publish the release. I'm worried that people will forget if we print the URL alone.

**Comment by jverkoey** [comment]
Perhaps we could have the terminal sit in a loop until it detects that the release was actually published?

**Comment by pingpongboss** [comment]
Ah good point. That is different from the others open-url cases i'm used
to.
